#ifndef PW_ECDSA_H
#define PW_ECDSA_H

#include <stddef.h>
#include <stdint.h>

/* ECDSA-P256-SHA256 sign with RFC 6979 deterministic k.
 * msg is hashed with SHA-256 internally. */
int ecdsa_p256_sha256_sign(const uint8_t priv[32],
                           const uint8_t* msg, size_t msg_n,
                           uint8_t out_r[32], uint8_t out_s[32]);

/* DER-encode (r, s) as SEQUENCE { INTEGER r, INTEGER s }. */
int ecdsa_p256_encode_der(const uint8_t r[32], const uint8_t s[32],
                          uint8_t* out, size_t out_cap);

/* Raw TLS-legacy/JWS style helper: out = r || s. TLS 1.3 CV uses DER. */
int ecdsa_p256_encode_raw64(const uint8_t r[32], const uint8_t s[32],
                            uint8_t out[64]);

/* ---------------------------------------------------------------- *
 *  ECDSA-P256 precompute pool (concurrency / latency optimisation)
 * ---------------------------------------------------------------- *
 *
 * Most of the cost of an ECDSA-P256 sign is the per-signature scalar
 * multiplication k*G plus the modular inverse k^-1. NEITHER depends
 * on the message or the private key — both can be computed in advance.
 *
 * A dedicated background "precompute" thread continuously refills a
 * fixed-size ring buffer with (r, kinv) tuples. ecdsa_p256_sha256_sign
 * does a non-blocking try-pop: on a hit it skips both k*G and inv,
 * reducing the sign cost from ~5-50 ms to a few mod-muls. On a miss
 * (pool empty, contended, or never initialised) it falls back to the
 * existing inline RFC 6979 deterministic-k path unchanged.
 *
 * The pool uses random k via getrandom() with rejection sampling
 * (never modulo reduction), which is RFC-compliant and avoids nonce
 * bias. Both code paths produce signatures of identical validity.
 *
 * Lifetime: process-singleton. The ring + mutex + condvars live for
 * the process lifetime once initialised; only the producer thread
 * can be stopped (via _shutdown). This avoids any free-vs-signer race.
 *
 * Init failure is non-fatal: every callsite gracefully falls back to
 * the inline path. Calling sign() before _init() is also safe — the
 * pool just appears empty and the inline path runs. */

/* Initialise the precompute pool with `pool_cap` slots and spawn ONE
 * producer thread. Idempotent: subsequent calls return 0 without
 * touching the existing pool. `pool_cap` must be >= 1; recommend
 * 32-128. Returns 0 on success, -1 on error (allocation, pthread,
 * or first-tuple self-test failure). */
int ecdsa_p256_precomp_init(uint32_t pool_cap);

/* Signal the producer thread to stop and join it. The pool itself
 * stays allocated for the rest of the process lifetime so signers
 * can still call sign() safely after shutdown — they simply always
 * fall back to the inline path. Idempotent. */
void ecdsa_p256_precomp_shutdown(void);

/* Snapshot of pool counters for observability. All fields may be 0
 * if the pool was never initialised. */
typedef struct {
    uint32_t pool_cap;
    uint32_t pool_depth;          /* current number of ready tuples */
    uint32_t pool_high_water;     /* peak pool_depth observed */
    uint64_t hits;                /* signs that used a pooled tuple */
    uint64_t misses;              /* signs that fell back (pool empty/contended) */
    uint64_t produced;            /* tuples generated by the producer */
    uint64_t producer_errors;     /* getrandom / scalar_mul failures */
    uint64_t s_zero_fallbacks;    /* fast-path produced s==0; very rare */
} ecdsa_p256_precomp_stats_t;
void ecdsa_p256_precomp_get_stats(ecdsa_p256_precomp_stats_t* out);

#endif
