apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"wfl-www","namespace":"wfl-www"},"spec":{"ports":[{"name":"https","port":443,"protocol":"TCP","targetPort":443},{"name":"http-redirect","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"wfl-www"},"type":"LoadBalancer"}}
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: wfl-www
  namespace: wfl-www
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.170.72
  clusterIPs:
  - 10.0.170.72
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    nodePort: 32421
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http-redirect
    nodePort: 30541
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tls-terminator
  sessionAffinity: None
  type: LoadBalancer
